"""add favorite_treat column to dogs table

Revision ID: 87ceab3d3ca4
Revises: c909284515f2
Create Date: 2024-12-10 12:53:31.382469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ceab3d3ca4'
down_revision = 'c909284515f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_treat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('favorite_treat')

    # ### end Alembic commands ###
